import json
import sys
import requests
import os
import cutlet
import time
from urllib.parse import quote

# Path to scraped Sekaipedia translations (generated by scrape_sekaipedia.py)
SEKAIPEDIA_TRANSLATIONS_FILE = 'sekaipedia_translations.json'

def load_sekaipedia_translations():
    """Load scraped Sekaipedia translations from JSON file.
    Returns a dict mapping Japanese title -> {romaji, english, page_title}.
    Returns empty dict if file doesn't exist."""
    if os.path.exists(SEKAIPEDIA_TRANSLATIONS_FILE):
        with open(SEKAIPEDIA_TRANSLATIONS_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print(f"Loaded {len(data)} Sekaipedia translations from {SEKAIPEDIA_TRANSLATIONS_FILE}")
        return data
    else:
        print(f"Warning: Sekaipedia translations file not found: {SEKAIPEDIA_TRANSLATIONS_FILE}")
        print("  Run 'python scrape_sekaipedia.py' first to generate it.")
        return {}

def read_json(file_path):
    """Read data from a JSON file."""
    with open(file_path, 'r', encoding='utf-8') as file:
        data = json.load(file)
    return data

def write_json(data, file_path):
    """Write data to a JSON file."""
    with open(file_path, 'w') as file:
        json.dump(data, file, indent=4)

def clean_filename(name):
    """Clean the filename by removing or replacing invalid characters."""
    invalid_chars = ['<', '>', ':', '"', '/', '\\', '|', '?', '*']
    for char in invalid_chars:
        name = name.replace(char, '_')
    return name

def get_english_translation(title, artist, song_id):
    """Try to get English translation for a song title."""
    # Simple heuristic: if title is already in English (mostly ASCII), return it
    if all(ord(c) < 128 for c in title):
        return title

    # Check known translations from config file
    from utils.config_manager import load_translations
    known_translations = load_translations()

    if title in known_translations:
        return known_translations[title]

    # For songs we don't have translations for, return empty string
    return ''

def get_romaji_override(title):
    """Override romaji for titles with special characters that cause conversion failures."""
    from utils.config_manager import load_romaji_overrides
    romaji_overrides = load_romaji_overrides()
    return romaji_overrides.get(title, None)

def main():
    output_file = 'output.json'
    data_url = 'https://dp4p6x0xfi5o9.cloudfront.net/maimai/data.json'

    # Download data from URL
    print(f"Downloading data from {data_url}...")
    try:
        response = requests.get(data_url)
        response.raise_for_status()
        data = response.json()
        print("Data downloaded successfully!")
    except requests.RequestException as e:
        print(f"Failed to download data: {e}")
        return

    # Load Sekaipedia scraped translations (primary source)
    sekaipedia = load_sekaipedia_translations()

    katsu = cutlet.Cutlet()
    katsu.use_foreign_spelling = False

    chart_data = []
    failed_romaji = []  # Track titles with failed romaji conversion
    sekaipedia_hits = 0  # Track how many titles used Sekaipedia data

    for song in data['songs']:

        # Ensure the directory for images exists
        image_dir = 'images'
        os.makedirs(image_dir, exist_ok=True)

        # Download and save the song image
        image_url = f"https://dp4p6x0xfi5o9.cloudfront.net/maimai/img/cover/{song['imageName']}"

        image_path = os.path.join(image_dir, clean_filename(song['songId']) + ".png")

        # Check if the image already exists to avoid re-downloading
        if os.path.exists(image_path):
            #print(f"Image for {song['imageName']} already exists at {image_path}, skipping download.")
            pass
        else:
            try:
                response = requests.get(image_url)
                response.raise_for_status()  # Raise an error for HTTP issues
                with open(image_path, 'wb') as img_file:
                    img_file.write(response.content)
                print(f"Downloaded image for {song['imageName']} to {image_path}")
            except requests.RequestException as e:
                print(f"Failed to download image {song['imageName']}: {e}")

        for chart in song['sheets']:
            if chart['difficulty'] == 'master' or chart['difficulty'] == 'remaster':
                image = clean_filename(song['songId']) + ".png"

                # --- Lookup translations: Sekaipedia first, then manual overrides ---
                sekai_entry = sekaipedia.get(song['title'])

                if sekai_entry and (sekai_entry.get('english') or sekai_entry.get('romaji')):
                    # Sekaipedia has data for this title
                    sekaipedia_hits += 1
                    english_title = sekai_entry.get('english', '')
                    romaji = sekai_entry.get('romaji', '')
                    # If Sekaipedia had no romaji, fall back to cutlet
                    if not romaji:
                        romaji_override = get_romaji_override(song['title'])
                        if romaji_override:
                            romaji = romaji_override
                        else:
                            romaji = katsu.romaji(song['title'])
                else:
                    # Sekaipedia didn't have it — use manual overrides / cutlet
                    english_title = get_english_translation(song['title'], song['artist'], song['songId'])

                    romaji_override = get_romaji_override(song['title'])
                    if romaji_override:
                        romaji = romaji_override
                    else:
                        romaji = katsu.romaji(song['title'])

                # Check for conversion failure: multiple consecutive question marks or 2+ question marks in short text
                if '??' in romaji or romaji.count('?') >= 3:
                    # Track failed conversion
                    if song['title'] not in [f['title'] for f in failed_romaji]:
                        failed_romaji.append({
                            'title': song['title'],
                            'artist': song['artist'],
                            'romaji_attempted': romaji,
                            'song_id': song['songId']
                        })
                    romaji = song['title']
                
                # Extract regions where the chart is available
                regions = []
                if 'regions' in chart:
                    region_data = chart['regions']
                    if region_data.get('jp', False):
                        regions.append('jp')
                    if region_data.get('intl', False):
                        regions.append('intl')
                    if region_data.get('usa', False):
                        regions.append('usa')
                
                chart_entry = {
                    'song_id': song['songId'],
                    'category': song['category'],
                    'title': song['title'],
                    'artist': song['artist'],
                    'version': chart['version'] if 'version' in chart else song.get('version', ''),
                    'type': chart['type'],
                    'difficulty': chart['difficulty'],
                    'level': chart['internalLevelValue'],
                    'image': image,
                    'romaji': romaji,
                    'english': english_title,
                    'regions': regions
                }
                chart_data.append(chart_entry)

    # Write data to the output JSON file
    write_json(chart_data, output_file)
    print(f"Data written to {output_file}")
    if sekaipedia:
        print(f"Used Sekaipedia translations for {sekaipedia_hits} song entries")
    
    # Write failed romaji conversions to separate file
    if failed_romaji:
        failed_file = 'failed_romaji.json'
        write_json(failed_romaji, failed_file)
        print(f"\nFound {len(failed_romaji)} titles with failed romaji conversion")
        print(f"Details written to {failed_file}")

if __name__ == "__main__":
    main()